export const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL || 'https://api.example.com';

export const endpoints = {
  aboutUs: {
    get: '/api/AboutUs/About-Us',
    add: '/api/AboutUs/Add-About-Us',
    update: '/api/AboutUs/Update-About-Us',
    addValue: '/api/AboutUs/Add-OneValue',
  },
  courses: {
    getAll: '/api/Course/All-Courses',
    getById: (id: string) => `/api/Course/get-Course/${id}`,
    findByName: (name: string) => `/api/Course/Find-Course/${name}`,
    filterByName: '/api/Course/Filter-Courses-by-name',
    filterByCategory: '/api/Course/Filter-Courses-by-category',
    filterByBool: '/api/Course/Filter-Courses-by-bool',
    create: '/api/Course/Create-Course',
    update: '/api/Course/Update-Course',
    addWWWL: '/api/Course/Add-WWWL',
    delete: (id: string) => `/api/Course/Delete-Course/${id}`,
    addLectures: '/api/Course/Add-Lectures-To-Course',
    removeLecture: '/api/Course/Remove-Lecture-from-Course',
    addInstructors: '/api/Course/Add-Instructors-To-Course',
  },
  departments: {
    getAllMain: '/api/MainDepartment/All-Departments',
    getMainById: (id: string) => `/api/MainDepartment/get-Department/${id}`,
    createMain: '/api/MainDepartment/Create-Department',
    updateMain: '/api/MainDepartment/Update-Department',
    deleteMain: (id: string) => `/api/MainDepartment/Delete-Department/${id}`,
    getAllSub: '/api/SubDepartment/All-Sub-Departments',
    getSubById: (id: string) => `/api/SubDepartment/get-Sub-Department/${id}`,
    getSubByMainId: (mainId: string) => `/api/SubDepartment/Get-By-Main-Deb/${mainId}`,
    createSub: '/api/SubDepartment/Create-Sub-Department',
    updateSub: '/api/SubDepartment/Update-Sub-Department',
    deleteSub: (id: string) => `/api/SubDepartment/Delete-Sub-Department/${id}`,
  },
  trainers: {
    getAll: '/api/Instructor/All-Instructors',
    getById: (id: string) => `/api/Instructor/get-Instructor/${id}`,
    create: '/api/Instructor/Create-Instructor',
    update: '/api/Instructor/Update-Instructor',
    delete: (id: string) => `/api/Instructor/Delete-Instructor/${id}`,
    videos: {
      getAll: '/api/Instructor/All-Videos',
      getByTrainerId: (trainerId: string) => `/api/Instructor/Videos/${trainerId}`,
      create: '/api/Instructor/Add-Video',
      update: '/api/Instructor/Update-Video',
      delete: (id: string) => `/api/Instructor/Delete-Video/${id}`,
    },
    articles: {
      getAll: '/api/Instructor/All-Articles',
      getByTrainerId: (trainerId: string) => `/api/Instructor/Articles/${trainerId}`,
      create: '/api/Instructor/Add-Article',
      update: '/api/Instructor/Update-Article',
      delete: (id: string) => `/api/Instructor/Delete-Article/${id}`,
    },
    reviews: {
      getAll: '/api/Instructor/All-Reviews',
      getByTrainerId: (trainerId: string) => `/api/Instructor/Reviews/${trainerId}`,
      create: '/api/Instructor/Add-Review',
      update: '/api/Instructor/Update-Review',
      delete: (id: string) => `/api/Instructor/Delete-Review/${id}`,
    },
  },
  partners: {
    getAll: '/api/Partner/All-Partners',
    getById: (id: string) => `/api/Partner/Get-Partner/${id}`,
    create: '/api/Partner/Add-Partner',
    update: '/api/Partner/Edit-Partner/{id}',
    delete: (id: string) => `/api/Partner/Delete-Partner/${id}`,
  },
  members: {
    getAll: '/api/Member/All-Members',
    getById: (id: string) => `/api/Member/Get-Member/${id}`,
    create: '/api/Member/Add-Member',
    update: '/api/Member/Edit-member/{id}',
    delete: (id: string) => `/api/Member/Delete-Member/${id}`,
  },
  sliders: {
    getAll: '/api/Slider/All-Slides',
    getById: (id: string) => `/api/Slider/Get-Slide/${id}`,
    create: '/api/Slider/Add-Slide',
    update: '/api/Slider/Edit-Slide/{id}',
    delete: (id: string) => `/api/Slider/Delete-Slide/${id}`,
  },
  messages: {
    getAll: '/api/Message/All-Messages',
    getById: (id: string) => `/api/Message/Get-Message/${id}`,
    create: '/api/Message/Add-Message',
    delete: (id: string) => `/api/Message/Delete-Message${id}`,
  },
  packages: {
    getAll: '/api/Package/All-Packages',
    create: '/api/Package/Create-Package',
    update: '/api/Package/Edit-Package/{id}',
    delete: (id: string) => `/api/Package/Delete-Package/${id}`,
  },
  trainings: {
    getAll: '/api/Training/All-Trainings',
    getById: (id: string) => `/api/Training/Get-Training/${id}`,
    getByUserId: (userId: string) => `/api/Training/Get-Trainings-by-UserId/${userId}`,
    create: '/api/Training/Add-Training',
    update: '/api/Training/Edit-Training/{id}',
    delete: (id: string) => `/api/Training/Delete-Training/${id}`,
  },
  lectures: {
    getAll: '/api/Lecture/All-Lectures',
    getById: (id: string) => `/api/Lecture/get-Lecture/${id}`,
    getByCourseId: (courseId: string) => `/api/Course/get-Course/${courseId}`,
    getByChapterId: (chapterId: string) => `/api/Lecture/get-Lectures-By-Chapter/${chapterId}`,
    create: '/api/Lecture/Create-Lecture',
    createChapter: '/api/Lecture/Create',
    removeLectureFromCourse: '/api/Course/Remove-Lecture-from-Course',
    delete: (id: string) => `/api/Lecture/Delete-Lecture/${id}`,
    comments: {
      getByLectureId: (lectureId: string) => `/api/Comment/Get-Comments-By-Lecture/${lectureId}`,
      delete: (id: string) => `/api/Comment/Delete-Comment/${id}`,
    },
    topics: {
      getByLectureId: (lectureId: string) => `/api/Topic/Get-Topics-By-Lecture/${lectureId}`,
      delete: (id: string) => `/api/Topic/Delete-Topic/${id}`,
    },
    questions: {
      create: '/api/Question/Create-Question',
    },
  },
  images: {
    getAll: '/api/Image/All-Images',
    getById: (id: string) => `/api/Image/Get-Image/${id}`,
    getByGroupId: (groupId: string) => `/api/Image/Get-Images-by-GroupId/${groupId}`,
    create: '/api/Image/Add-Image',
    update: '/api/Image/Edit-Image{id}',
    delete: (id: string) => `/api/Image/Delete-Image${id}`,
  },
  imageGroups: {
    getAll: '/api/ImageGroup/All-ImageGroup',
    getById: (id: string) => `/api/ImageGroup/Get-Image/${id}`,
    create: '/api/ImageGroup/Add-ImageGroup',
    update: '/api/ImageGroup/Edit-ImageGroup/{id}',
    delete: (id: string) => `/api/ImageGroup/Delete-ImageGroup/${id}`,
  },
  users: {
    getAll: '/api/user/GetAllUsers',
    getById: (id: string) => `/api/user/Edit-User?id=${id}`,
    register: '/api/user/Register',
    login: '/api/login/login',
    updatePassword: '/api/user/Update-Password',
    forgotPassword: '/api/user/Forget-Password',
    resetPassword: '/api/user/Reset-Password',
    checkCode: '/api/user/Check-Code',
    delete: (id: string) => `/api/user/Delete-user${id}`,
  },
  subscribe: {
    getAll: '/api/Subscribe/Get-all',
    checkMail: '/api/Subscribe/Check-Mail',
    delete: (id: string) => `/api/Subscribe/Delete-Subscribe/${id}`,
  },
  requests: {
    training: {
      getAll: '/api/Request/All-Training-Requests',
      getById: (id: string) => `/api/Request/get-Training-Request/${id}`,
      create: '/api/Request/Create-Training-Request',
      updateStatus: '/api/Request/Update-Training-Request-Status',
    },
    beTrainer: {
      getAll: '/api/Request/All-Be-Trainer-Requests',
      getById: (id: string) => `/api/Request/get-Be-Trainer-Request/${id}`,
      create: '/api/Request/Create-Be-Trainer-Request',
      updateStatus: '/api/Request/Update-Be-Trainer-Request-Status',
    },
    userTraining: {
      getByCourseId: (courseId: string) => `/api/user/Get-by-CourseId/${courseId}`,
      removeUserFromCourse: '/api/Course/Remove-User-From-Course',
    },
    contact: {
      getAll: '/api/ContactUs/All-Messages',
      getById: (id: string) => `/api/ContactUs/get-Message/${id}`,
      create: '/api/ContactUs/Send-Message',
    },
    emailSubscription: {
      getAll: '/api/EmailSubscription/All-Subscriptions',
      create: '/api/EmailSubscription/Subscribe',
    },
  },
  imagesCenter: {
    groups: {
      getAll: '/api/ImageGroup/All-ImageGroup',
      getById: (id: string) => `/api/ImageGroup/Get-Image/${id}`,
      create: '/api/ImageGroup/Add-ImageGroup',
      update: '/api/ImageGroup/Edit-ImageGroup/{id}',
      delete: (id: string) => `/api/ImageGroup/Delete-ImageGroup/${id}`,
    },
    images: {
      getAll: '/api/Image/All-Images',
      getById: (id: string) => `/api/Image/Get-Image/${id}`,
      getByGroupId: (groupId: string) => `/api/Image/Get-Images-by-GroupId/${groupId}`,
      create: '/api/Image/Add-Image',
      update: '/api/Image/Edit-Image{id}',
      delete: (id: string) => `/api/Image/Delete-Image${id}`,
    },
  },
} as const;
