export const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL || 'https://api.example.com';

export const endpoints = {
  aboutUs: {
    get: '/api/AboutUs/About-Us',
    add: '/api/AboutUs/Add-About-Us',
    update: '/api/AboutUs/Update-About-Us',
    addValue: '/api/AboutUs/Add-OneValue',
  },
  courses: {
    getAll: '/api/Course/All-Courses',
    getById: (id: string) => `/api/Course/get-Course/${id}`,
    findByName: (name: string) => `/api/Course/Find-Course/${name}`,
    filterByName: '/api/Course/Filter-Courses-by-name',
    filterByCategory: '/api/Course/Filter-Courses-by-category',
    filterByBool: '/api/Course/Filter-Courses-by-bool',
    create: '/api/Course/Create-Course',
    update: '/api/Course/Update-Course',
    addWWWL: '/api/Course/Add-WWWL',
    delete: (id: string) => `/api/Course/Delete-Course/${id}`,
  },
  departments: {
    getAllMain: '/api/Department/All-Main-Departments',
    getMainById: (id: string) => `/api/Department/get-Main-Department/${id}`,
    createMain: '/api/Department/Create-Main-Department',
    updateMain: '/api/Department/Update-Main-Department',
    deleteMain: (id: string) => `/api/Department/Delete-Main-Department/${id}`,
    getAllSub: '/api/Department/All-Sub-Departments',
    getSubById: (id: string) => `/api/Department/get-Sub-Department/${id}`,
    getSubByMainId: (mainId: string) => `/api/SubDepartment/Get-By-Main-Deb/${mainId}`,
    createSub: '/api/Department/Create-Sub-Department',
    updateSub: '/api/Department/Update-Sub-Department',
    deleteSub: (id: string) => `/api/Department/Delete-Sub-Department/${id}`,
  },
  trainers: {
    getAll: '/api/Instructor/All-Instructors',
    getById: (id: string) => `/api/Instructor/get-Instructor/${id}`,
    create: '/api/Instructor/Create-Instructor',
    update: '/api/Instructor/Update-Instructor',
    delete: (id: string) => `/api/Instructor/Delete-Instructor/${id}`,
  },
  partners: {
    getAll: '/api/Partner/All-Partners',
    getById: (id: string) => `/api/Partner/get-Partner/${id}`,
    create: '/api/Partner/Create-Partner',
    update: '/api/Partner/Update-Partner',
    delete: (id: string) => `/api/Partner/Delete-Partner/${id}`,
  },
  team: {
    getAll: '/api/Team/All-Team',
    getById: (id: string) => `/api/Team/get-Team/${id}`,
    create: '/api/Team/Create-Team',
    update: '/api/Team/Update-Team',
    delete: (id: string) => `/api/Team/Delete-Team/${id}`,
  },
  sliders: {
    getAll: '/api/Slider/All-Sliders',
    getById: (id: string) => `/api/Slider/get-Slider/${id}`,
    create: '/api/Slider/Create-Slider',
    update: '/api/Slider/Update-Slider',
    delete: (id: string) => `/api/Slider/Delete-Slider/${id}`,
  },
  requests: {
    training: {
      getAll: '/api/Request/All-Training-Requests',
      getById: (id: string) => `/api/Request/get-Training-Request/${id}`,
      create: '/api/Request/Create-Training-Request',
      updateStatus: '/api/Request/Update-Training-Request-Status',
    },
    beTrainer: {
      getAll: '/api/Request/All-Be-Trainer-Requests',
      getById: (id: string) => `/api/Request/get-Be-Trainer-Request/${id}`,
      create: '/api/Request/Create-Be-Trainer-Request',
      updateStatus: '/api/Request/Update-Be-Trainer-Request-Status',
    },
    userTraining: {
      getByCourseId: (courseId: string) => `/api/user/Get-by-CourseId/${courseId}`,
      removeUserFromCourse: '/api/Course/Remove-User-From-Course',
    },
    contact: {
      getAll: '/api/ContactUs/All-Messages',
      getById: (id: string) => `/api/ContactUs/get-Message/${id}`,
      create: '/api/ContactUs/Send-Message',
    },
    emailSubscription: {
      getAll: '/api/EmailSubscription/All-Subscriptions',
      create: '/api/EmailSubscription/Subscribe',
    },
  },
  imagesCenter: {
    groups: {
      getAll: '/api/ImagesGroup/All-Groups',
      getById: (id: string) => `/api/ImagesGroup/get-Group/${id}`,
      create: '/api/ImagesGroup/Create-Group',
      update: '/api/ImagesGroup/Update-Group',
      delete: (id: string) => `/api/ImagesGroup/Delete-Group/${id}`,
    },
    images: {
      getAll: '/api/Image/All-Images',
      getByGroupId: (groupId: string) => `/api/Image/get-Images-By-Group/${groupId}`,
      create: '/api/Image/Create-Image',
      delete: (id: string) => `/api/Image/Delete-Image/${id}`,
    },
  },
  users: {
    getAll: '/api/User/All-Users',
    getById: (id: string) => `/api/User/get-User/${id}`,
    register: '/api/User/Register',
    login: '/api/User/Login',
    updateProfile: '/api/User/Update-Profile',
    changePassword: '/api/User/Change-Password',
    forgotPassword: '/api/User/Forgot-Password',
    resetPassword: '/api/User/Reset-Password',
  },
} as const;
