export * from './config';
export * from './client';
export * from './course.service';
export * from './about-us.service';
export * from './trainer.service';
export * from './department.service';
export * from './request.service';
export * from './common.service';
export * from './user.service';
